services:
  - type: web
    name: compra-mais
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gevent --workers 2 --timeout 0 --keep-alive 75
    envVars:
      - key: COMPRA_PLUS_DB
        value: /var/data/compra_plus.db
